[package]
name = "person_registration"
version = "0.1.0"
edition = "2021"
descrition = "Person registration for Brazil documents"
licence = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rand = "0.8.0"